### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by ksadjad** [giftig/s3-browser#15]
Hi guys. I just installed this via pip and I'm facing this error:
```
Traceback (most recent call last):
  File "/home/sadjad/.local/bin/s3-browser", line 6, in <module>
    from s3_browser.cli import main
  File "/home/sadjad/.local/lib/python2.7/site-packages/s3_browser/cli.py", line 44
    print('\x1b[31m', msg, '\x1b[0m', file=sys.stderr)
                                          ^
SyntaxError: invalid syntax

```

can you help me with that?

**Comment by giftig** [comment]
Hi @ksadjad looks like you're trying to install it on python2, which is now deprecated. I've packaged it to indicate python 3.2+ as a requirement, so I would expect pip to tell you it can't install it on python2, but if you're using an old version of pip it's possible it doesn't support the `python_requires` attribute.

If you install it on python 3.2+ it should work fine.
